
import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ivanm
 */
public class Main extends javax.swing.JFrame {
    String[] operation;
    String[] numbers = {"0", "1", "2", "3", "4", "5", "6", "7", "8", "9"};
    String[] symbols = {"x","+", "-", "÷"};
    boolean isDark = false;
    ArrayList<Integer> results  = new ArrayList<Integer>();
    ArrayList<String> remaining  = new ArrayList<String>();
    String temp = "";
    String previous_operation = "";
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        background = new javax.swing.JPanel();
        preview = new javax.swing.JLabel();
        B7 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        separator = new javax.swing.JSeparator();
        BDiv = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        BMult = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        BMin = new javax.swing.JButton();
        BAC = new javax.swing.JButton();
        B0 = new javax.swing.JButton();
        BEquals = new javax.swing.JButton();
        BSum = new javax.swing.JButton();
        BTheme = new javax.swing.JButton();
        Previous = new javax.swing.JLabel();
        BDel = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(410, 600));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setPreferredSize(new java.awt.Dimension(387, 1480));

        preview.setBackground(new java.awt.Color(0, 0, 0));
        preview.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        preview.setForeground(new java.awt.Color(0, 0, 0));
        preview.setText("Enter your operation :)");

        B7.setBackground(new java.awt.Color(255, 255, 255));
        B7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        B7.setForeground(new java.awt.Color(0, 0, 0));
        B7.setText("7");
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });

        B9.setBackground(new java.awt.Color(255, 255, 255));
        B9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        B9.setForeground(new java.awt.Color(0, 0, 0));
        B9.setText("9");
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ActionPerformed(evt);
            }
        });

        B8.setBackground(new java.awt.Color(255, 255, 255));
        B8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        B8.setForeground(new java.awt.Color(0, 0, 0));
        B8.setText("8");
        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ActionPerformed(evt);
            }
        });

        BDiv.setBackground(new java.awt.Color(153, 204, 255));
        BDiv.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BDiv.setForeground(new java.awt.Color(0, 0, 0));
        BDiv.setText("÷");
        BDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDivActionPerformed(evt);
            }
        });

        B4.setBackground(new java.awt.Color(255, 255, 255));
        B4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        B4.setForeground(new java.awt.Color(0, 0, 0));
        B4.setText("4");
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });

        B5.setBackground(new java.awt.Color(255, 255, 255));
        B5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        B5.setForeground(new java.awt.Color(0, 0, 0));
        B5.setText("5");
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });

        B6.setBackground(new java.awt.Color(255, 255, 255));
        B6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        B6.setForeground(new java.awt.Color(0, 0, 0));
        B6.setText("6");
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });

        BMult.setBackground(new java.awt.Color(153, 204, 255));
        BMult.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BMult.setForeground(new java.awt.Color(0, 0, 0));
        BMult.setText("x");
        BMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMultActionPerformed(evt);
            }
        });

        B1.setBackground(new java.awt.Color(255, 255, 255));
        B1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        B1.setForeground(new java.awt.Color(0, 0, 0));
        B1.setText("1");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        B2.setBackground(new java.awt.Color(255, 255, 255));
        B2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        B2.setForeground(new java.awt.Color(0, 0, 0));
        B2.setText("2");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        B3.setBackground(new java.awt.Color(255, 255, 255));
        B3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        B3.setForeground(new java.awt.Color(0, 0, 0));
        B3.setText("3");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });

        BMin.setBackground(new java.awt.Color(153, 204, 255));
        BMin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BMin.setForeground(new java.awt.Color(0, 0, 0));
        BMin.setText("-");
        BMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMinActionPerformed(evt);
            }
        });

        BAC.setBackground(new java.awt.Color(255, 51, 51));
        BAC.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BAC.setForeground(new java.awt.Color(0, 0, 0));
        BAC.setText("AC");
        BAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACActionPerformed(evt);
            }
        });

        B0.setBackground(new java.awt.Color(255, 255, 255));
        B0.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        B0.setForeground(new java.awt.Color(0, 0, 0));
        B0.setText("0");
        B0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B0ActionPerformed(evt);
            }
        });

        BEquals.setBackground(new java.awt.Color(255, 255, 255));
        BEquals.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BEquals.setForeground(new java.awt.Color(0, 0, 0));
        BEquals.setText("=");
        BEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEqualsActionPerformed(evt);
            }
        });

        BSum.setBackground(new java.awt.Color(153, 204, 255));
        BSum.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BSum.setForeground(new java.awt.Color(0, 0, 0));
        BSum.setText("+");
        BSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSumActionPerformed(evt);
            }
        });

        BTheme.setBackground(new java.awt.Color(255, 255, 255));
        BTheme.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BTheme.setForeground(new java.awt.Color(0, 0, 0));
        BTheme.setText("Switch Theme");
        BTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BThemeActionPerformed(evt);
            }
        });

        Previous.setForeground(new java.awt.Color(0, 0, 0));

        BDel.setBackground(new java.awt.Color(255, 204, 153));
        BDel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BDel.setForeground(new java.awt.Color(0, 0, 0));
        BDel.setText("del");
        BDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(BTheme)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Previous, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(preview))
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BDel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(separator, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backgroundLayout.createSequentialGroup()
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(backgroundLayout.createSequentialGroup()
                                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BAC, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28)
                                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(B0, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(28, 28, 28)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BMult, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BMin, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BSum, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(24, 24, 24))))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(BTheme, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Previous, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(preview, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(BDel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BMult, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BMin, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BSum, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B0, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BAC, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(938, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMultActionPerformed
        // TODO add your handling code here:
        typeNumber(BMult);
    }//GEN-LAST:event_BMultActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        // TODO add your handling code here:
        typeNumber(B6);
    }//GEN-LAST:event_B6ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        // TODO add your handling code here:
        typeNumber(B5);
    }//GEN-LAST:event_B5ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        // TODO add your handling code here:
        typeNumber(B4);
    }//GEN-LAST:event_B4ActionPerformed

    private void BDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDivActionPerformed
        // TODO add your handling code here:
        typeNumber(BDiv);
    }//GEN-LAST:event_BDivActionPerformed

    private void B8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8ActionPerformed
        // TODO add your handling code here:
        typeNumber(B8);
    }//GEN-LAST:event_B8ActionPerformed

    private void B9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9ActionPerformed
        // TODO add your handling code here:
        typeNumber(B9);
    }//GEN-LAST:event_B9ActionPerformed

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed
        // TODO add your handling code here:
        typeNumber(B7);
    }//GEN-LAST:event_B7ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
        typeNumber(B1);
    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
        typeNumber(B2);
    }//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        // TODO add your handling code here:
        typeNumber(B3);
    }//GEN-LAST:event_B3ActionPerformed

    private void BMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMinActionPerformed
        // TODO add your handling code here:
        typeNumber(BMin);
    }//GEN-LAST:event_BMinActionPerformed

    private void BACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACActionPerformed
        // TODO add your handling code here:
        typeNumber(BAC);
    }//GEN-LAST:event_BACActionPerformed

    private void B0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B0ActionPerformed
        // TODO add your handling code here:
        typeNumber(B0);
    }//GEN-LAST:event_B0ActionPerformed

    private void BEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEqualsActionPerformed
        // TODO add your handling code here:
        typeNumber(BEquals);
    }//GEN-LAST:event_BEqualsActionPerformed

    private void BSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSumActionPerformed
        // TODO add your handling code here:
        typeNumber(BSum);
    }//GEN-LAST:event_BSumActionPerformed

    private void BThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BThemeActionPerformed
        // TODO add your handling code here:
        setTheme();
    }//GEN-LAST:event_BThemeActionPerformed

    private void BDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDelActionPerformed
        // TODO add your handling code here:
        typeNumber(BDel);
    }//GEN-LAST:event_BDelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B0;
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JButton BAC;
    private javax.swing.JButton BDel;
    private javax.swing.JButton BDiv;
    private javax.swing.JButton BEquals;
    private javax.swing.JButton BMin;
    private javax.swing.JButton BMult;
    private javax.swing.JButton BSum;
    private javax.swing.JButton BTheme;
    private javax.swing.JLabel Previous;
    private javax.swing.JPanel background;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel preview;
    private javax.swing.JSeparator separator;
    // End of variables declaration//GEN-END:variables



public void typeNumber(javax.swing.JButton button){
    
    boolean esEntero = false;
    
    
    for (int i = 0; i < this.numbers.length; i++){
        if (this.numbers[i].equals(button.getText())){
            esEntero = true;
        }
    }
    
    if (esEntero){
        addNumberToPreview(button);
        this.temp += button.getText();
        
    }
    
    else {
        this.remaining.add(this.temp);
        this.temp = "";
        
        if(button.getText().equals("x")){
            this.temp = "x";
            addNumberToPreview(button);
            this.remaining.add(this.temp);
            this.temp = "";
            
        }
        if(button.getText().equals("+")){
            this.temp = "+";
            addNumberToPreview(button);
            this.remaining.add(this.temp);
            this.temp = "";
        }
        if(button.getText().equals("-")) {
            this.temp = "-";
            addNumberToPreview(button);
            this.remaining.add(this.temp);
            this.temp = "";
        }
        if(button.getText().equals("÷")) {
            this.temp = "÷";
            addNumberToPreview(button);
            this.remaining.add(this.temp);
            this.temp = "";
        }
        
        if (button.getText().equals("AC")){
            this.Previous.setText("");
            this.preview.setText("Enter your operation :)");
            this.remaining = new ArrayList<String>();
            this.temp = "";            
        }
        if(button.getText().equals("del")){
            if (this.preview.getText().equals("Enter your operation :)")){
                this.preview.setText("");
            } else {
                if (this.preview.getText().length() >= 1){
                    this.preview.setText(this.preview.getText().substring(0, (this.preview.getText().length() - 1)));
                    if(this.preview.getText().length() == 0){
                        this.preview.setText("Enter your operation :)");
                    }
                } else {
                    this.preview.setText("Enter your operation :)");
                    
                }
                
            }
            
        }
        if(button.getText().equals("=")){
            this.temp = "";
            readInput() ;
        }
        
        
        
        
    }
}

public void readInput(){
     // This function will assign the current input text into a variable
     
    int result = 0;
    this.previous_operation = "";
    this.Previous.setText("");
    
    for (int i = 0; i < this.remaining.size(); i++){
        this.previous_operation += this.remaining.get(i);
        for(int j = 0; j < this.symbols.length; j++){
            
            
            if (this.remaining.get(i).equals(this.symbols[j])){
                if(result == 0){
                    if(this.remaining.get(i).equals("+")) {
                        result = sumNumber(Integer.valueOf(this.remaining.get(i - 1)), Integer.valueOf(this.remaining.get(i + 1)) );
                        this.preview.setText(String.valueOf(result));
                    } else if (this.remaining.get(i).equals("-")){
                        result = minusNumber(Integer.valueOf(this.remaining.get(i - 1)),Integer.valueOf(this.remaining.get(i + 1)) );
                        this.preview.setText(String.valueOf(result));
                        
                    } else if (this.remaining.get(i).equals("x")){
                        result = multiNumber(Integer.valueOf(this.remaining.get(i - 1)),Integer.valueOf(this.remaining.get(i + 1)) );
                        this.preview.setText(String.valueOf(result));
                        
                    } else if(this.remaining.get(i).equals("÷")){
                        result = divNumber(Integer.valueOf(this.remaining.get(i - 1)),Integer.valueOf(this.remaining.get(i + 1)) );
                        this.preview.setText(String.valueOf(result));
                        
                    }
                    
                    
                } else {
                    if(this.remaining.get(i).equals("+")) {
                        result = sumNumber(result, Integer.valueOf(this.remaining.get(i + 1)) );
                        this.preview.setText(String.valueOf(result));
                        
                    } else if (this.remaining.get(i).equals("-")){
                        result = minusNumber(result, Integer.valueOf(this.remaining.get(i + 1)) );
                        this.preview.setText(String.valueOf(result));
                        
                    } else if (this.remaining.get(i).equals("x")){
                        result = multiNumber(result,Integer.valueOf(this.remaining.get(i + 1)) );
                        this.preview.setText(String.valueOf(result));
                        
                    } else if(this.remaining.get(i).equals("÷")){
                        result = divNumber(result,Integer.valueOf(this.remaining.get(i + 1)) );
                        this.preview.setText(String.valueOf(result));
                        
                    }
                    
                }
                
            }
            
           
            
        }
    }
    
    // Display last operation on preview
    this.previous_operation += "=" + String.valueOf(result);
    this.Previous.setText(this.previous_operation);
    
}

public int sumNumber(int number1, int number2){
    return (number1+number2);
}

public int minusNumber(int number1, int number2){
    
    return (number1 - number2);
}

public int multiNumber(int number1, int number2){
    return (number1*number2);
}

public int divNumber(int number1, int number2){
    int resultado = 0;
    
    if (number1 == 0 || number2 == 0){
        if (number1 == 0 && number2 != 0) resultado = number2;
        if (number2 == 0 && number1 != 0) resultado = number1;
        this.preview.setText("Operation not allowed :(");
    } else {
        resultado = number1/number2;
    }
    
    return resultado;
    
}


public void addNumberToPreview(javax.swing.JButton button){
    if (this.preview.getText().length() < 18 || this.preview.getText().equals("Enter your operation :)")){
    
        if (!this.preview.getText().equals("Enter your operation :)")){
            this.preview.setText(this.preview.getText()+ button.getText());
        } else {
            this.preview.setText(button.getText());
        }
    }
}

public void setTheme(){
    if (this.isDark){
        
        // Set panel background to white
        this.background.setBackground(Color.white);
        
        // Set label font color to black
        this.preview.setForeground(Color.black);
        this.Previous.setForeground(Color.black);
        
         // Set button font color to black
        this.B0.setForeground(Color.black);
        this.B1.setForeground(Color.black);
        this.B2.setForeground(Color.black);
        this.B3.setForeground(Color.black);
        this.B4.setForeground(Color.black);
        this.B5.setForeground(Color.black);
        this.B6.setForeground(Color.black);
        this.B7.setForeground(Color.black);
        this.B8.setForeground(Color.black);
        this.B9.setForeground(Color.black);
        this.BSum.setForeground(Color.black);
        this.BMin.setForeground(Color.black);
        this.BMult.setForeground(Color.black);
        this.BDiv.setForeground(Color.black);
        this.BEquals.setForeground(Color.black);
        this.BAC.setForeground(Color.black);
        this.BDel.setForeground(Color.black);
        this.BTheme.setForeground(Color.black);
        
        // Set button background to white
        this.B0.setBackground(Color.white);
        this.B1.setBackground(Color.white);
        this.B2.setBackground(Color.white);
        this.B3.setBackground(Color.white);
        this.B4.setBackground(Color.white);
        this.B5.setBackground(Color.white);
        this.B6.setBackground(Color.white);
        this.B7.setBackground(Color.white);
        this.B8.setBackground(Color.white);
        this.B9.setBackground(Color.white);
        this.BEquals.setBackground(Color.white);
        this.BTheme.setBackground(Color.white);
        
        // Disable dark mode
        this.isDark = false;
        
    } else {
        // Set panel background to black
        this.background.setBackground(Color.black);
        
        // Set label font color to white
        this.preview.setForeground(Color.white);
        this.Previous.setForeground(Color.white);
        
        // Set button background to gray
        this.B0.setBackground(Color.gray);
        this.B1.setBackground(Color.gray);
        this.B2.setBackground(Color.gray);
        this.B3.setBackground(Color.gray);
        this.B4.setBackground(Color.gray);
        this.B5.setBackground(Color.gray);
        this.B6.setBackground(Color.gray);
        this.B7.setBackground(Color.gray);
        this.B8.setBackground(Color.gray);
        this.B9.setBackground(Color.gray);
        this.BEquals.setBackground(Color.gray);
        this.BTheme.setBackground(Color.gray);
        
        // Set button font color to white
        this.B0.setForeground(Color.white);
        this.B1.setForeground(Color.white);
        this.B2.setForeground(Color.white);
        this.B3.setForeground(Color.white);
        this.B4.setForeground(Color.white);
        this.B5.setForeground(Color.white);
        this.B6.setForeground(Color.white);
        this.B7.setForeground(Color.white);
        this.B8.setForeground(Color.white);
        this.B9.setForeground(Color.white);
        this.BSum.setForeground(Color.white);
        this.BMin.setForeground(Color.white);
        this.BMult.setForeground(Color.white);
        this.BDiv.setForeground(Color.white);
        this.BEquals.setForeground(Color.white);
        this.BAC.setForeground(Color.white);
        this.BDel.setForeground(Color.white);
        this.BTheme.setForeground(Color.white);
        
        // Enable dark mode
        this.isDark = true;
        
    }
}




}
